/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Simpus;

/**
 *
 * @author Ailsa
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogout = new javax.swing.JButton();
        jLabelBuku = new javax.swing.JLabel();
        jLabelSkripsi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLogout.setBackground(new java.awt.Color(255, 119, 119));
        jButtonLogout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 80, 30));

        jLabelBuku.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabelBuku.setText("  BUKU");
        jLabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBukuMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 200, 100));

        jLabelSkripsi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSkripsi.setText(" SKRIPSI");
        jLabelSkripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSkripsiMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSkripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 190, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/Homepage (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBukuMouseClicked
        // TODO add your handling code here:
        GUIBuku buku = new GUIBuku();
        buku.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelBukuMouseClicked

    private void jLabelSkripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkripsiMouseClicked
        // TODO add your handling code here:
        GUISkripsi skripsi = new GUISkripsi();
        skripsi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSkripsiMouseClicked

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBuku;
    private javax.swing.JLabel jLabelSkripsi;
    // End of variables declaration//GEN-END:variables
}
